Repository grocy/grocy, pull requests merged in 2020-04, with the labels that each got.

#687 Fix errors with disabled feature flag STOCK_PRICE_TRACKING
  public/viewjs/inventory.js
  public/viewjs/purchase.js
  public/viewjs/stockentryform.js
Labels: ui-bug

#688 Preset the stock qu with the purchase qu on new products.
  public/viewjs/productform.js
Labels: enhancement

#697 PSR7-decoupled rework of authentication fixup
  middleware/SessionAuthMiddleware.php
  routes.php
Labels: enhancement

#703 Create the backup tarball explicitly before invoking tar
  update.sh
Labels: enhancement

#704 Add missing form validation on presetting QU id stock
  public/viewjs/productform.js
Labels: ui-bug

#710 Fixup: paths for localization file existence checks
  services/LocalizationService.php
Labels: bug

#733 Add camera picker button
  public/viewjs/components/barcodescanner.js
Labels: enhancement

#745 Remove NodeJS dependency check
  helpers/PrerequisiteChecker.php
Labels: bug

#763 Fixed Timezone in CalendarApiController
  controllers/CalendarApiController.php
Labels: enhancement

#776 Recipe Pages UI updates
  localization/strings.pot
  public/css/grocy.css
  public/viewjs/recipeform.js
  views/components/numberpicker.blade.php
  views/components/productpicker.blade.php
  views/recipeform.blade.php
  views/recipes.blade.php
Labels: enhancement

#767 Purchase Price Hints
  public/viewjs/components/productcard.js
  public/viewjs/purchase.js
  views/purchase.blade.php
Labels: enhancement

#784 Link to respective page on Calendar Event Click
  public/css/grocy.css
  public/viewjs/calendar.js
  services/CalendarService.php
Labels: enhancement

#793 Make GetUriParam work with special characters (eg. "&")
  public/js/extensions.js
Labels: bug

#788 Create Inverse QU Conversions
  public/viewjs/quantityunitconversionform.js
  views/quantityunitconversionform.blade.php
Labels: enhancement

#795 Recipe updates
  controllers/RecipesController.php
  public/css/grocy.css
  public/viewjs/recipeform.js
  public/viewjs/recipes.js
  views/recipeform.blade.php
  views/recipes.blade.php
Labels: enhancement

#796 fix product shopping location for edits
  views/productform.blade.php
Labels: ui-bug

#802 Fixed fix for #570
  migrations/0102.sql
Labels: bug

#806 Added SQLite check for #805
  helpers/PrerequisiteChecker.php
Labels: enhancement
