Repository grocy/grocy, pull requests merged in 2020-10, with the labels that each got.

#1018 Ui fixes
  public/viewjs/recipes.js
  views/productform.blade.php
  views/recipes.blade.php
Labels: ui-bug

#1026 added button to add expired products to shoppinglist
  controllers/StockApiController.php
  grocy.openapi.json
  localization/strings.pot
  public/viewjs/shoppinglist.js
  routes.php
  services/StockService.php
  views/shoppinglist.blade.php
Labels: enhancement

#1049 Improvements
  controllers/StockApiController.php
  public/js/grocy_dbchangedhandling.js
  public/viewjs/consume.js
  public/viewjs/recipeform.js
  public/viewjs/shoppinglistitemform.js
  services/RecipesService.php
  services/StockService.php
  views/components/locationpicker.blade.php
  views/consume.blade.php
  views/equipment.blade.php
  views/layout/default.blade.php
  views/products.blade.php
  views/shoppinglist.blade.php
  views/shoppinglistitemform.blade.php
Labels: bug, ui-bug

#1051 fix expiring filter
  views/stockoverview.blade.php
Labels: ui-bug

#1045 Value information
  localization/strings.pot
  migrations/0105.sql
  public/viewjs/stockoverview.js
  views/stockoverview.blade.php
Labels: enhancement

#1057 fix for price and total price
  public/viewjs/components/productcard.js
  public/viewjs/purchase.js
Labels: ui-bug

#1056 add purchased date to purchase
  config-dist.php
  controllers/StockApiController.php
  public/viewjs/purchase.js
  public/viewjs/stocksettings.js
  views/purchase.blade.php
  views/stocksettings.blade.php
Labels: enhancement

#1067 Fix night mode
  public/css/grocy_night_mode.css
Labels: enhancement

#1062 typo
  config-dist.php
  controllers/StockController.php
  migrations/0116.sql
  public/viewjs/stockentries.js
  public/viewjs/stocksettings.js
  views/stocksettings.blade.php
Labels: enhancement

#1077 Allow price up to 4 decimals instead of 2
  config-dist.php
  public/js/grocy.js
  public/viewjs/consume.js
  public/viewjs/inventory.js
  public/viewjs/productform.js
  public/viewjs/purchase.js
  public/viewjs/recipeform.js
  public/viewjs/recipeposform.js
  public/viewjs/shoppinglistitemform.js
  public/viewjs/stockentryform.js
  public/viewjs/stocksettings.js
  public/viewjs/transfer.js
  services/StockService.php
  views/choreform.blade.php
  views/components/numberpicker.blade.php
  views/components/productamountpicker.blade.php
  views/consume.blade.php
  views/inventory.blade.php
  views/mealplan.blade.php
  views/productbarcodesform.blade.php
  views/productform.blade.php
  views/purchase.blade.php
  views/quantityunitconversionform.blade.php
  views/quantityunitpluraltesting.blade.php
  views/recipeform.blade.php
  views/recipeposform.blade.php
  views/recipes.blade.php
  views/shoppinglistitemform.blade.php
  views/stockentryform.blade.php
  views/stocksettings.blade.php
  views/transfer.blade.php
Labels: enhancement

#1078 Display productCard when clicking item on shopping list
  public/viewjs/shoppinglist.js
  views/shoppinglist.blade.php
Labels: enhancement

#1079 stock entries button on product card
  public/viewjs/components/productcard.js
  views/components/productcard.blade.php
Labels: enhancement

#1093 Fixes #1092: Repair QR-Codes for API-Keys
  public/viewjs/manageapikeys.js
Labels: ui-bug

#1081 inventory fix for quFactorPurchaseToStock - defaults to product details
  services/StockService.php
Labels: bug

#1102 Add purchased date to inventory
  controllers/StockApiController.php
  localization/strings.pot
  public/viewjs/inventory.js
  services/StockService.php
  views/inventory.blade.php
  views/stocksettings.blade.php
Labels: enhancement

#1103 dialogs for shopping list
  public/viewjs/shoppinglist.js
  public/viewjs/shoppinglistform.js
  public/viewjs/shoppinglistitemform.js
  views/shoppinglist.blade.php
Labels: enhancement

#1108 delete duplicate
  grocy.openapi.json
Labels: enhancement

#1109 Unit stock name in the mealplan
  public/viewjs/mealplan.js
Labels: ui-bug

#1110 AddProduct Method Fix For SelfProduction
  services/StockService.php
Labels: bug

#1111 limit to normal recipes
  controllers/StockController.php
Labels: ui-bug
