Repository grocy/grocy, pull requests merged in 2020-08, with the labels that each got.

#801 Qu factor purchase to stock & Product Barcode Details
  controllers/StockApiController.php
  controllers/StockController.php
  grocy.openapi.json
  localization/strings.pot
  migrations/0103.sql
  migrations/0104.sql
  public/viewjs/components/productcard.js
  public/viewjs/components/productpicker.js
  public/viewjs/consume.js
  public/viewjs/inventory.js
  public/viewjs/mealplan.js
  public/viewjs/productbarcodesform.js
  public/viewjs/productform.js
  public/viewjs/productgroupform.js
  public/viewjs/productgroups.js
  public/viewjs/products.js
  public/viewjs/purchase.js
  public/viewjs/quantityunitconversionform.js
  public/viewjs/stockentries.js
  public/viewjs/stockentryform.js
  public/viewjs/stockoverview.js
  public/viewjs/transfer.js
  routes.php
  services/DemoDataGeneratorService.php
  services/StockService.php
  views/components/numberpicker.blade.php
  views/components/productcard.blade.php
  views/components/productpicker.blade.php
  views/consume.blade.php
  views/inventory.blade.php
  views/productbarcodesform.blade.php
  views/productform.blade.php
  views/productgroups.blade.php
  views/products.blade.php
  views/purchase.blade.php
  views/recipes.blade.php
  views/stockentries.blade.php
  views/stockentryform.blade.php
  views/stockoverview.blade.php
  views/transfer.blade.php
Labels: enhancement

#945 Fix base path computation when running in subdirectory
  helpers/UrlManager.php
Labels: bug

#939 Run multi instances by making GROCY_DATAPATH customizable
  public/index.php
Labels: enhancement

#880 WIP: Fix typo on "Consumed Amount" localization string
  localization/strings.pot
  views/locationcontentsheet.blade.php
Labels: ui-bug

#927 Improve Performance
  controllers/StockController.php
  migrations/0105.sql
  migrations/0106.sql
  services/StockService.php
  views/stockoverview.blade.php
Labels: enhancement

#933 use last Chore-Log when determining the next assigned person
  services/ChoresService.php
Labels: bug

#876 Make product amount picker locale independent
  public/viewjs/components/productamountpicker.js
Labels: ui-bug

#921 Refactor Authentication and add proxy-authentication
  app.php
  config-dist.php
  middleware/ApiKeyAuthMiddleware.php
  middleware/AuthMiddleware.php
  middleware/DefaultAuthMiddleware.php
  middleware/ReverseProxyAuthMiddleware.php
  middleware/SessionAuthMiddleware.php
  routes.php
  services/UsersService.php
  views/layout/default.blade.php
Labels: enhancement

#855 Fix grocy/grocy#834
  config-dist.php
  migrations/0107.sql
Labels: bug

#844 Additional configuration options for Quagga2
  config-dist.php
  public/viewjs/components/barcodescanner.js
Labels: enhancement

#960 [WIP] Implemented basic permissions
  .devtools/transifex_download.bat
  .tx/config
  app.php
  config-dist.php
  controllers/BaseController.php
  controllers/BatteriesApiController.php
  controllers/ChoresApiController.php
  controllers/ExceptionController.php
  controllers/FilesApiController.php
  controllers/GenericEntityApiController.php
  controllers/RecipesApiController.php
  controllers/StockApiController.php
  controllers/TasksApiController.php
  controllers/Users/PermissionMissingException.php
  controllers/Users/User.php
  controllers/UsersApiController.php
  controllers/UsersController.php
  localization/en/permissions.po
  localization/permissions.pot
  localization/strings.pot
  migrations/0111.sql
  public/css/grocy.css
  public/js/grocy.js
  public/viewjs/userpermissions.js
  routes.php
  services/LocalizationService.php
  services/UsersService.php
  views/batteries.blade.php
  views/batteriesjournal.blade.php
  views/batteriesoverview.blade.php
  views/choresjournal.blade.php
  views/choresoverview.blade.php
  views/components/userpermission_select.blade.php
  views/errors/403.blade.php
  views/errors/404.blade.php
  views/errors/500.blade.php
  views/errors/base.blade.php
  views/layout/default.blade.php
  views/stockoverview.blade.php
  views/userpermissions.blade.php
  views/users.blade.php
Labels: enhancement

#965 Include location and shopping_location_id when opening products
  services/StockService.php
Labels: bug

#973 Run database-Migrations in right order
  services/DatabaseMigrationService.php
Labels: bug

#976 Locales: use http-accept-language or cookie
  .devtools/transifex_download.bat
  .tx/config
  README.md
  app.php
  config-dist.php
  controllers/BaseController.php
  controllers/UsersController.php
  localization/en/locales.po
  localization/locales.pot
  localization/strings.pot
  middleware/CorsMiddleware.php
  middleware/LocaleMiddleware.php
  public/js/grocy.js
  public/viewjs/usersettings.js
  routes.php
  services/BaseService.php
  services/DatabaseService.php
  services/DemoDataGeneratorService.php
  services/LocalizationService.php
  views/layout/default.blade.php
  views/usersettings.blade.php
Labels: enhancement

#977 Add user-field-type "file"
  controllers/FilesApiController.php
  localization/userfield_types.pot
  migrations/0112.sql
  public/js/extensions.js
  public/viewjs/components/userfieldsform.js
  public/viewjs/equipmentform.js
  routes.php
  services/UserfieldsService.php
  views/components/userfields_tbody.blade.php
  views/components/userfieldsform.blade.php
Labels: enhancement
